# Build settings
markdown: redcarpet
redcarpet:
          extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments
gems:
  - jemoji

# Site settings
title: "UoM Bioinfo Soc"
description: "Bioinformatics Society at the University of Manchester Faculty of Life Sciences. We organise training events and seminars in computational biology."

email: uombioinfosoc@gmail.com
#blog logo
logo: "/assets/images/bioinfo_soc_logo_300x300.jpg"
# blog cover
cover: "/assets/images/bioinfo_soc_logo_banner.jpg"
footer_cover: "/assets/images/bioinfo_soc_logo_banner_fade.jpg"

name: 'University of Manchester Bioinformatics Society'
author: 'UoM Bioinfo Soc'
author_image: "/assets/images/bioinfo_soc_logo_300x300.jpg"

paginate:	5

url: "http://UoMBioinfoSoc.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@UoMBioinfoSoc'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/UoMBioinfoSoc
    desc: Follow us on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/UoMBioinfoSoc
    desc: Keep up to date via Facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/UoMBioinfoSoc
    desc:	Find source code for our talks, workshops and this site on GitHub
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
